// Package updatesrecovery provides an optional plugin that persists and
// restores Telegram update state (pts, qts, date, seq) across restarts,
// reconnects, and network failures, and recovers missed updates by calling
// [updates.getDifference] when a PTS gap is detected.
//
// # Why a plugin?
//
// mtgo's core stays lightweight: it receives updates and dispatches them to
// handlers, nothing more. Update recovery — state persistence, gap detection,
// and getDifference calls — is opt-in via this plugin. Users who do not need
// durable update tracking pay zero cost.
//
// # Usage
//
//	store, _ := sqlite.Open("bot.db")
//	client, _ := telegram.NewClient(apiID, apiHash, &telegram.Config{
//	    Storage:    store,
//	    SessionName: "my_bot",
//	})
//
//	client.Use(updatesrecovery.New(updatesrecovery.Storage(store, "my_bot")))
//
// The plugin tracks pts/qts/date/seq for every incoming update, persists them
// to the provided [Store] on a debounce, and calls updates.getDifference when
// a gap is detected or after a reconnect.
//
// # When to enable
//
// Enable this plugin when your bot must not miss updates across restarts or
// brief network outages. For fire-and-forget bots or webhook-style processing
// where occasional gaps are acceptable, the overhead is unnecessary.
package updatesrecovery

import (
	"github.com/mtgo-labs/storage"
)

// State holds the Telegram update sequence numbers that the plugin tracks
// and persists across restarts.
type State struct {
	// Pts is the common update sequence number.
	Pts int32
	// Qts is the sequence number for updates generated by the current user.
	Qts int32
	// Date is the timestamp of the last applied update.
	Date int32
	// Seq is the event sequence number.
	Seq int32
}

// Store is the minimal persistence interface for update state.
// Implementations must be safe for concurrent use.
//
// The provided [Storage] function adapts any [storage.UpdateStateStore]
// (SQLite, PostgreSQL, MongoDB, or custom) to this interface.
type Store interface {
	// SaveState persists the given state.
	SaveState(state *State) error
	// LoadState returns the last persisted state, or (nil, nil) if none.
	LoadState() (*State, error)
}

// --- storage.UpdateStateStore adapter ---

type storageAdapter struct {
	store     storage.UpdateStateStore
	sessionID string
}

// Storage wraps a [storage.UpdateStateStore] to satisfy the [Store] interface.
// Pass the session name (same as Config.SessionName) so state is scoped
// correctly.
func Storage(store storage.UpdateStateStore, sessionID string) Store {
	return &storageAdapter{store: store, sessionID: sessionID}
}

func (a *storageAdapter) SaveState(s *State) error {
	return a.store.SaveUpdateState(&storage.UpdateState{
		SessionID: a.sessionID,
		Pts:       s.Pts,
		Qts:       s.Qts,
		Date:      s.Date,
		Seq:       s.Seq,
	})
}

func (a *storageAdapter) LoadState() (*State, error) {
	saved, err := a.store.LoadUpdateState(a.sessionID)
	if err != nil {
		return nil, err
	}
	if saved == nil {
		return nil, nil
	}
	return &State{
		Pts:  saved.Pts,
		Qts:  saved.Qts,
		Date: saved.Date,
		Seq:  saved.Seq,
	}, nil
}

// --- in-memory store (testing / ephemeral) ---

// NewMemoryStore returns a non-persistent [Store] suitable for testing or
// ephemeral sessions.
func NewMemoryStore() Store { return &memoryStore{} }

type memoryStore struct {
	state *State
}

func (m *memoryStore) SaveState(s *State) error {
	cp := *s
	m.state = &cp
	return nil
}

func (m *memoryStore) LoadState() (*State, error) {
	if m.state == nil {
		return nil, nil
	}
	cp := *m.state
	return &cp, nil
}
